Repository 8thejulge/thejulge, pull requests merged in 2025-06, with the labels that each got.

#9 Feat: header 및 footer 기능과 UI 구현
  .vscode/settings.json
  package-lock.json
  package.json
  public/email.png
  public/facebook.png
  public/file.svg
  public/globe.svg
  public/insta.png
  public/logo.png
  public/next.svg
  public/search.png
  public/vercel.svg
  public/window.svg
  src/app/api/axios.ts
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/components/Alarm.tsx
  src/components/AlarmDropDown.tsx
  src/components/Footer.tsx
  src/components/GuestMenu.tsx
  src/components/Header.tsx
  src/components/Search.tsx
  src/components/UserMenu.tsx
  src/lib/use-auth.tsx
  src/types/types.ts
Labels: ✨feat

#18 chore: layout.tsx 불필요한 코드 정리
  src/app/layout.tsx
Labels: 🛠️refacory

#19 [15-feat] 사장페이지 가게정보 상세페이지 제작
  src/app/owner/Register/page.tsx
  src/app/owner/page.tsx
  src/app/owner/register-store/page.tsx
Labels: ✨feat

#23 chore: api와 컴포넌트 폴더 구조를 변경하는 작업
  src/app/layout.tsx
  src/components/common/Alarm/Alarm.tsx
  src/components/common/Alarm/AlarmDropDown.tsx
  src/components/common/Footer/Footer.tsx
  src/components/common/Header/GuestMenu.tsx
  src/components/common/Header/Header.tsx
  src/components/common/Header/UserMenu.tsx
  src/components/common/Search/Search.tsx
  src/components/member/.gitkeep
  src/components/owner/.gitkeep
  src/lib/api/axios.ts
  src/lib/hooks/use-auth.tsx
Labels: 🛠️refactor

#26 Feat/job list UI
  .github/workflows/deploy.yml
  .github/workflows/lighthouse.yml
  .prettierrc
  package-lock.json
  package.json
  src/app/notice/page.tsx
  src/components/notice/detailfilter.tsx
  src/components/notice/filter.tsx
Labels: ✨feat

#28 feat: 공고등록 UI 완성
  public/closeIcon.png
  src/app/owner/register-job/page.tsx
Labels: ✨feat, 🎨 style

#29 [feat-21]/ login, sign ui 완성
  src/app/layout.tsx
  src/app/login/page.tsx
  src/app/sign/page.tsx
  src/components/LayoutWrapper.tsx
  src/components/LoginSignAuthFormWrapper.tsx
  src/components/common/Header/GuestMenu.tsx
Labels: ✨feat

#30 feat: 알바님 - 내 프로필 등록하기 페이지 ui 완성
  src/app/member/profile/page.tsx
  src/app/member/register/page.tsx
  src/components/member/Modal.tsx
Labels: ✨feat, 🎨 style

#33 Feat: 공고 상세페이지 구현 1차
  next.config.ts
  public/arrow-orange.png
  public/arrow.png
  public/location.png
  public/time.png
  src/app/notice/[shopId]/[noticeId]/page.tsx
  src/components/common/Alarm/AlarmDropDown.tsx
  src/components/notice-detail/ApplyButton.tsx
  src/components/notice-detail/LatestNotice.tsx
  src/components/notice-detail/NoticeCard.tsx
  src/components/notice-detail/NoticeImage.tsx
  src/components/notice-detail/NoticeInfo.tsx
  src/components/notice-detail/PayRate.tsx
  src/components/notice-detail/WorkHour.tsx
  src/lib/api/axios.ts
Labels: ✨feat

#35 Feat: 사장님 공고 상세 UI 구현
  public/arrow-up-bold.png
  public/clock-icon.png
  public/close-icon.png
  public/location-icon.png
  src/app/owner/job-detail/ApplicantTable.tsx
  src/app/owner/job-detail/StoreDetail.tsx
  src/app/owner/job-detail/page.tsx
  src/app/owner/job-detail/pagenation.tsx
  src/app/owner/register-job/page.tsx
Labels: ✨feat, 🎨 style

#37 Feat: 공고 상세페이지 모달 기능 구현
  public/alert.png
  public/check.png
  src/components/notice-detail/ApplyButton.tsx
  src/components/notice-detail/modal/NoticeModal.tsx
  src/components/notice-detail/modal/NoticeModalItem.tsx
  src/types/types.ts
Labels: ✨feat

#39 Feat: 사장님 공고등록 유효성 검사 및 모달 연결
  src/app/owner/register-job/page.tsx
Labels: ✨feat

#45 feat: useAuth 새로고침 시 상태 유지되도록 업데이트
  src/lib/hooks/use-auth.tsx
  src/lib/hooks/use-token.tsx
Labels: ✨feat

#58 Feat: 사장님 공고 등록 구현
  src/app/owner/owner-store-detail/MyJobPost.tsx
  src/app/owner/owner-store-detail/MyStore.tsx
  src/app/owner/owner-store-detail/RegisteredJob.tsx
  src/app/owner/owner-store-detail/page.tsx
  src/app/owner/owner-store-detail/store/MyStoreNoticesStore.ts
  src/app/owner/owner-store-detail/store/ShopDetailStore.ts
  src/app/owner/register-job/page.tsx
Labels: ✨feat

#59 Feat: 공고 상세 페이지 및 header 기능 구현
  src/app/globals.css
  src/app/login/page.tsx
  src/app/notice/[shopId]/[noticeId]/page.tsx
  src/components/common/Alarm/Alarm.tsx
  src/components/common/Alarm/AlarmCard.tsx
  src/components/common/Alarm/AlarmDropDown.tsx
  src/components/common/Header/Header.tsx
  src/components/common/Header/UserMenu.tsx
  src/components/common/Header/input-validator.tsx
  src/components/common/Search/Search.tsx
  src/components/notice-detail/ApplyButton.tsx
  src/components/notice-detail/LatestNotice.tsx
  src/components/notice-detail/NoticeCard.tsx
  src/components/notice-detail/NoticeImage.tsx
  src/components/notice-detail/NoticeInfo.tsx
  src/components/notice-detail/WorkHour.tsx
  src/components/notice-detail/modal/NoticeModalItem.tsx
  src/lib/hooks/notice-detail/use-cancel-id.tsx
  src/types/types.ts
Labels: ✨feat

#62 Feat : 알바님 내프로필 페이지 2차 구현
  public/left-arrow-disabled.png
  public/left-arrow.png
  public/right-arrow.png
  src/app/member/myprofile/page.tsx
  src/app/member/register/page.tsx
  src/components/member/myprofile/ApplyTable.tsx
  src/components/member/myprofile/Pagination.tsx
Labels: ✨feat, 🎨 style

#67 [Fix:65] 상세 필터 적용
  src/app/notice/page.tsx
  src/components/notice/detailfilter.tsx
  src/lib/hooks/zustand.ts
Labels: 🐞bug

#74 Feat/41 owner job detail
  public/right-arrow-disabled.png
  src/app/owner/job-detail/ApplicantTable.tsx
  src/app/owner/job-detail/ModalConfirm.tsx
  src/app/owner/job-detail/StoreDetail.tsx
  src/app/owner/job-detail/[shopId]/[noticeId]/page.tsx
  src/app/owner/job-detail/page.tsx
  src/app/owner/job-detail/pagenation.tsx
  src/app/owner/job-detail/stores/jobPostStore.tsx
  src/app/owner/owner-store-detail/MyJobPost.tsx
  src/app/owner/owner-store-detail/MyStore.tsx
  src/app/owner/owner-store-detail/RegisteredJob.tsx
  src/app/owner/owner-store-detail/page.tsx
  src/app/owner/owner-store-detail/store/MyStoreNoticesStore.ts
  src/app/owner/register-job/page.tsx
Labels: ✨feat

#80 Feat: 사장님 - 공고 수정 구현
  src/app/owner/job-detail/ApplicantTable.tsx
  src/app/owner/job-detail/StoreDetail.tsx
  src/app/owner/job-detail/stores/jobPostStore.tsx
  src/app/owner/owner-store-detail/MyJobPost.tsx
  src/app/owner/owner-store-detail/MyStore.tsx
  src/app/owner/register-job/page.tsx
Labels: ✨feat

#88 fix: 라우터 링크 수정
  src/app/owner/owner-store-detail/MyStore.tsx
Labels: ✨feat, 🐞bug

#89 feat: 마감공고, 지난공고 UI 처리 및 로컬스토리지 수정
  src/app/owner/job-detail/ApplicantTable.tsx
  src/app/owner/job-detail/StoreDetail.tsx
  src/app/owner/job-detail/[shopId]/[noticeId]/page.tsx
  src/app/owner/owner-store-detail/MyJobPost.tsx
  src/app/owner/owner-store-detail/MyStore.tsx
  src/app/owner/owner-store-detail/RegisteredJob.tsx
  src/app/owner/register-job/page.tsx
  src/app/owner/register-store/page.tsx
  src/components/common/Header/UserMenu.tsx
  src/lib/hooks/use-auth.tsx
Labels: ✨feat

#92 feat: 이미지 관련 경고 메시지 제거 및 라우트 가드 설정
  src/app/login/page.tsx
  src/app/notice/[shopId]/[noticeId]/page.tsx
  src/app/owner/owner-store-detail/page.tsx
  src/app/owner/page.tsx
  src/app/owner/register-job/page.tsx
  src/app/owner/register-store/page.tsx
  src/components/common/Footer/Footer.tsx
  src/components/common/Header/Header.tsx
  src/components/notice-detail/NoticeCard.tsx
  src/components/notice-detail/NoticeImage.tsx
  src/components/notice-detail/NoticeInfo.tsx
  src/components/notice-detail/PayRate.tsx
  src/components/notice-detail/WorkHour.tsx
Labels: ✨feat

#96 fix: useSearchParams 제거
  src/app/result/page.tsx
Labels: 🐞bug

#97 Fix/94 owner store move error
  src/app/owner/Register/page.tsx
  src/app/owner/job-detail/StoreDetail.tsx
  src/app/owner/owner-store-detail/MyJobPost.tsx
  src/app/owner/owner-store-detail/MyStore.tsx
  src/app/owner/owner-store-detail/RegisteredJob.tsx
  src/app/owner/owner-store-detail/store/MyStoreNoticesStore.ts
  src/app/owner/register-job/page.tsx
  src/app/owner/register-store/page.tsx
Labels: 🐞bug

#100 style: 검색 결과 페이지 UI 수정
  src/app/result/page.tsx
  src/components/common/Search/Search.tsx
Labels: ✨feat

#105 Fix: 파비콘 적용 및 홈 화면 UI 개선
  public/favicon.ico
  src/app/favicon.ico
  src/app/layout.tsx
  src/app/notice/page.tsx
  src/app/result/page.tsx
  src/components/notice-detail/LatestNotice.tsx
  src/components/notice-detail/NoticeCard.tsx
  src/components/notice/detailfilter.tsx
  src/components/notice/filter.tsx
Labels: 🐞bug, 🎨 style

#107 Fix/ 공고 상세 및 헤더 마지막 수정
  src/app/result/page.tsx
  src/components/common/Search/Search.tsx
  src/components/notice-detail/NoticeCard.tsx
  src/components/notice-detail/PayRate.tsx
Labels: 🐞bug

#110 fix: 코드 누락 수정
  src/components/common/Search/Search.tsx
Labels: 🐞bug

#112 feat: 111-alarm 호출 코드 수정
  src/components/common/Header/UserMenu.tsx
Labels: ✨feat
